// Exports prototype/themes.js (the single theme source) into the Android app:
//   android/app/src/main/assets/styles/<id>.json and <id>-car.json
//   android/app/src/main/java/.../theme/ThemeTokens.kt
// Run: node tools/export-android.mjs
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const root = path.resolve(import.meta.dirname, "..");
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root, "prototype", "themes.js"), "utf8"), ctx);
const { THEMES: ALL_THEMES, buildStyle } = ctx.window.Overworld;
// Paused themes stay in themes.js but don't ship in the app.
const THEMES = Object.fromEntries(Object.entries(ALL_THEMES).filter(([, t]) => !t.paused));

const app = path.join(root, "android", "app", "src", "main");
const stylesDir = path.join(app, "assets", "styles");
fs.rmSync(stylesDir, { recursive: true, force: true });
fs.mkdirSync(stylesDir, { recursive: true });

for (const t of Object.values(THEMES)) {
  for (const car of [false, true]) {
    // Themes with their own map lettering read the bundled glyphs (tools/make_glyphs.py).
    const style = buildStyle(t, { car, glyphs: "asset://glyphs/{fontstack}/{range}.pbf" });
    // The app draws the route itself (themed, below the labels), so drop the web route.
    delete style.sources.route;
    style.layers = style.layers.filter((l) => l.source !== "route");
    if (style.layers.some((l) => l.paint && l.paint["fill-pattern"])) {
      style.sprite = "asset://sprites/overworld";
    }
    const file = path.join(stylesDir, `${t.id}${car ? "-car" : ""}.json`);
    fs.writeFileSync(file, JSON.stringify(style));
  }
}

// ---- Kotlin tokens ----
function color(c) {
  if (!c) return "Color.Transparent";
  const m = c.match(/^rgba?\(([^)]+)\)$/);
  if (m) {
    const [r, g, b, a = "1"] = m[1].split(",").map((x) => x.trim());
    return `Color(${r}, ${g}, ${b}, ${Math.round(parseFloat(a) * 255)})`;
  }
  return `Color(0xFF${c.slice(1).toUpperCase()})`;
}
const esc = (s) => JSON.stringify(s);
const entries = Object.values(THEMES).map((t) => {
  const h = t.hud, r = t.map.route;
  return `  OverworldTheme(
      id = ${esc(t.id)},
      name = ${esc(t.name)},
      blurb = ${esc(t.blurb)},
      dark = ${t.dark},
      font = HudFont.${h.fontKey.toUpperCase()},
      uppercase = ${h.upper},
      land = ${color(t.map.land)},
      routeLine = ${color(r.line)},
      routeCasing = ${color(r.casing)},
      routeGlow = ${r.glow ? color(r.glow) : "null"},
      puckFill = ${color(t.marker.fill)},
      puckShape = ${esc(t.marker.shape || "chevron")},
      puckShade = ${t.marker.shade ? color(t.marker.shade) : "null"},
      puckStroke = ${color(t.marker.stroke)},
      blipShape = ${esc(t.blip?.shape || "diamond")},
      blipFill = ${color(t.blip?.fill || h.accent)},
      blipCenter = ${color(t.blip?.center || t.marker.stroke)},
      blipStroke = ${color(t.blip?.stroke || t.marker.stroke)},
      hudBg = ${color(h.bg)},
      hudFg = ${color(h.fg)},
      hudSub = ${color(h.sub)},
      hudAccent = ${color(h.accent)},
      hudGood = ${color(h.good)},
      hudBorder = ${color(h.border)},
      carCard = ${color(h.card)},
      page = ${color(t.page)},
      paperOverlay = ${t.overlay === "paper"},
  )`;
});
const kt = `// Generated by tools/export-android.mjs from prototype/themes.js. Do not edit by hand.
package com.thealgothrim.overworld.theme

import androidx.compose.ui.graphics.Color

val THEMES: List<OverworldTheme> = listOf(
${entries.join(",\n")},
)
`;
const ktFile = path.join(app, "java", "com", "thealgothrim", "overworld", "theme", "ThemeTokens.kt");
fs.mkdirSync(path.dirname(ktFile), { recursive: true });
fs.writeFileSync(ktFile, kt);
console.log(`exported ${Object.keys(THEMES).length} themes x 2 styles, tokens -> ${path.relative(root, ktFile)}`);
