// Exports prototype/themes.js (the single theme source) into the Android app:
//   android/app/src/main/assets/styles/<id>.json and <id>-car.json (and <id>-<variant>[-car].json
//   for time-of-day palettes)
//   android/app/src/main/java/.../theme/ThemeTokens.kt
// Run: node tools/export-android.mjs
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const root = path.resolve(import.meta.dirname, "..");
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root, "prototype", "themes.js"), "utf8"), ctx);
const { THEMES: ALL_THEMES, buildStyle } = ctx.window.Overworld;
// Paused themes stay in themes.js but don't ship in the app.
const THEMES = Object.fromEntries(Object.entries(ALL_THEMES).filter(([, t]) => !t.paused));

const app = path.join(root, "android", "app", "src", "main");
const stylesDir = path.join(app, "assets", "styles");
fs.rmSync(stylesDir, { recursive: true, force: true });
fs.mkdirSync(stylesDir, { recursive: true });

let files = 0;
for (const t of Object.values(THEMES)) {
  // The base palette, then any time-of-day variants (GTA VI's dusk and night): <id>-<variant>.json.
  for (const variant of [null, ...Object.keys(t.variants || {})]) {
    for (const car of [false, true]) {
      // Themes with their own map lettering read the bundled glyphs (tools/make_glyphs.py).
      const style = buildStyle(t, { car, variant, glyphs: "asset://glyphs/{fontstack}/{range}.pbf" });
      // The app draws the route itself (themed, below the labels), so drop the web route.
      delete style.sources.route;
      style.layers = style.layers.filter((l) => l.source !== "route");
      if (style.layers.some((l) => (l.paint && l.paint["fill-pattern"]) || l.id === "poi-blips")) {
        style.sprite = "asset://sprites/overworld";
      }
      const file = path.join(stylesDir, `${t.id}${variant ? `-${variant}` : ""}${car ? "-car" : ""}.json`);
      fs.writeFileSync(file, JSON.stringify(style));
      files++;
    }
  }
}

// ---- Kotlin tokens ----
function color(c) {
  if (!c) return "Color.Transparent";
  const m = c.match(/^rgba?\(([^)]+)\)$/);
  if (m) {
    const [r, g, b, a = "1"] = m[1].split(",").map((x) => x.trim());
    return `Color(${r}, ${g}, ${b}, ${Math.round(parseFloat(a) * 255)})`;
  }
  return `Color(0xFF${c.slice(1).toUpperCase()})`;
}
const esc = (s) => JSON.stringify(s);
const entries = Object.values(THEMES).map((t) => {
  const h = t.hud, r = t.map.route;
  const variants = Object.entries(t.variants || {}).map(
      ([name, v]) => `${esc(name)} to MapVariant(page = ${color(v.page)}, land = ${color(v.map.land)}, dark = ${v.dark})`
  );
  return `  OverworldTheme(
      id = ${esc(t.id)},
      name = ${esc(t.name)},
      skin = Skin.${(t.skin || "gta").toUpperCase()},
      blurb = ${esc(t.blurb)},
      dark = ${t.dark},
      font = HudFont.${h.fontKey.toUpperCase()},
      uppercase = ${h.upper},
      land = ${color(t.map.land)},
      routeLine = ${color(r.line)},
      routeCasing = ${color(r.casing)},
      routeGlow = ${r.glow ? color(r.glow) : "null"},
      routeFade = ${r.fade || 0}.0,
      routeEdge = ${r.edge || 0}f,
      blipShape = ${esc(t.blip?.shape || "diamond")},
      blipFill = ${color(t.blip?.fill || h.accent)},
      blipCenter = ${color(t.blip?.center || t.marker.stroke)},
      blipStroke = ${color(t.blip?.stroke || t.marker.stroke)},
      hudBg = ${color(h.bg)},
      hudFg = ${color(h.fg)},
      hudSub = ${color(h.sub)},
      hudAccent = ${color(h.accent)},
      hudGood = ${color(h.good)},
      hudBorder = ${color(h.border)},
      carCard = ${color(h.card)},
      page = ${color(t.page)},
      paperOverlay = ${t.overlay === "paper"},
      variants = ${variants.length ? `mapOf(${variants.join(", ")})` : "emptyMap()"},
      buildings3d = ${!!t.map.buildings3d},
  )`;
});
const kt = `// Generated by tools/export-android.mjs from prototype/themes.js. Do not edit by hand.
package com.thealgothrim.overworld.theme

import androidx.compose.ui.graphics.Color

val THEMES: List<OverworldTheme> = listOf(
${entries.join(",\n")},
)
`;
const ktFile = path.join(app, "java", "com", "thealgothrim", "overworld", "theme", "ThemeTokens.kt");
fs.mkdirSync(path.dirname(ktFile), { recursive: true });
fs.writeFileSync(ktFile, kt);
console.log(`exported ${Object.keys(THEMES).length} themes, ${files} styles, tokens -> ${path.relative(root, ktFile)}`);
