"""Fetch a real driving route from the public OSRM demo server and write it as
prototype/route.js for the offline-safe prototype (no routing call at runtime).

Usage: python tools/make_route.py [from_lon,from_lat] [to_lon,to_lat] [from_name] [to_name]
Default: Chhatarpur -> India Gate, Delhi.
"""
import json
import math
import sys
import urllib.request
from pathlib import Path

FROM = sys.argv[1] if len(sys.argv) > 1 else "77.1749,28.5068"
TO = sys.argv[2] if len(sys.argv) > 2 else "77.2295,28.6129"
FROM_NAME = sys.argv[3] if len(sys.argv) > 3 else "Chhatarpur"
TO_NAME = sys.argv[4] if len(sys.argv) > 4 else "India Gate"

url = (
    f"https://router.project-osrm.org/route/v1/driving/{FROM};{TO}"
    "?overview=full&geometries=geojson&steps=true"
)
req = urllib.request.Request(url, headers={"User-Agent": "overworld-maps-prototype"})
data = json.load(urllib.request.urlopen(req, timeout=30))
route = data["routes"][0]
coords = [[round(x, 6), round(y, 6)] for x, y in route["geometry"]["coordinates"]]


def haversine(a, b):
    r = 6371008.8
    lon1, lat1, lon2, lat2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    h = math.sin((lat2 - lat1) / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2
    return 2 * r * math.asin(math.sqrt(h))


cum = [0.0]
for i in range(1, len(coords)):
    cum.append(cum[-1] + haversine(coords[i - 1], coords[i]))


def icon_for(kind, mod):
    if kind == "arrive":
        return "arrive"
    if kind in ("roundabout", "rotary"):
        return "roundabout"
    if not mod or mod == "straight":
        return "straight"
    return mod.replace(" ", "-")


def text_for(step, dest):
    m = step["maneuver"]
    kind, mod = m["type"], m.get("modifier", "")
    road = step.get("name") or step.get("ref") or ""
    onto = f" onto {road}" if road else ""
    if kind == "arrive":
        return f"Arrive at {dest}"
    if kind == "depart":
        return f"Head out{onto}"
    if kind in ("roundabout", "rotary"):
        n = m.get("exit")
        return f"At the roundabout, take exit {n}{onto}" if n else f"At the roundabout, continue{onto}"
    if kind == "fork":
        return f"Keep {mod.replace('slight ', '')}{onto}"
    if kind == "merge":
        return f"Merge{onto}"
    if kind in ("on ramp", "off ramp"):
        return f"Take the ramp{onto}"
    if kind in ("new name", "continue") and mod in ("", "straight"):
        return f"Continue{onto}" if road else "Continue straight"
    if kind == "continue":
        return f"Keep {mod.replace('slight ', '')}{onto}"
    return f"Turn {mod}{onto}" if mod and mod != "straight" else f"Continue{onto}"


steps, idx = [], 0
for step in route["legs"][0]["steps"]:
    kind = step["maneuver"]["type"]
    if kind in ("exit roundabout", "exit rotary"):
        continue  # folded into the roundabout instruction
    loc = step["maneuver"]["location"]
    best, best_d = idx, float("inf")
    for j in range(idx, len(coords)):
        d = haversine(coords[j], loc)
        if d < best_d:
            best, best_d = j, d
        if d > best_d + 400:
            break
    idx = best
    steps.append({
        "at": round(cum[best], 1),
        "icon": icon_for(kind, step["maneuver"].get("modifier", "")),
        "road": step.get("name") or step.get("ref") or "",
        "text": text_for(step, TO_NAME),
    })

out = {
    "from": FROM_NAME,
    "to": TO_NAME,
    "distance": round(cum[-1], 1),
    "duration": round(route["duration"]),
    "coords": coords,
    "cum": [round(c, 1) for c in cum],
    "steps": steps,
}
target = Path(__file__).resolve().parent.parent / "prototype" / "route.js"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(
    "// Generated by tools/make_route.py from the public OSRM demo server. Do not edit by hand.\n"
    f"window.OW_ROUTE = {json.dumps(out, separators=(',', ':'))};\n",
    encoding="utf-8",
)
print(f"{FROM_NAME} -> {TO_NAME}: {out['distance'] / 1000:.1f} km, {len(coords)} points, {len(steps)} steps")
for s in steps:
    print(f"  {s['at']:>8.0f} m  {s['icon']:<12} {s['text']}")
